services:
  maestro.server:
    image: maestro.server
    build:
      context: .
      dockerfile: Maestro.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SEQ_SERVER_URL=http://seq:5341
    ports:
      - "5000:8080"
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data

volumes:
  seq-data:

